- hosts: web
  remote_user: projecter

  tasks:

  - name: Delete old website version
    file: path=/home/projecter/web state=absent

  - name: Create web directory
    file: path=/home/projecter/web state=directory

  - name: Upload new build
    copy:
      src: ../dist/
      dest: /home/projecter/web/
      
  - name: Create .htaccess
    copy:
      content: ""
      dest: /home/projecter/web/.htaccess

  - name: Modify .htaccess
    blockinfile:
      path: /home/projecter/web/.htaccess
      block: |
        RewriteEngine On
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-l
        RewriteRule ^.*$ / [L,QSA]
